Automate conformance testing on PR using zot
Signed-off-by: Josh Dolitsky <josh@dolit.ski>

diff --git a/.github/workflows/build-pr.yml b/.github/workflows/build-pr.yml
--- a/.github/workflows/build-pr.yml
+++ b/.github/workflows/build-pr.yml
@@ -23,8 +23,32 @@ jobs:
           go-version: ${{ matrix.go }}
 
       - name: run tests
+        id: tests
         run: |
           export PATH="$(go env GOPATH)/bin:${PATH}"
           make install.tools
           make .gitvalidation
           make docs conformance
+
+          set +e
+          make conformance-ci
+          CONFORMANCE_RC="$?"
+          set -e
+          if [[ -f report.html ]]; then
+            echo "Found report.html."
+            echo "has-report=true" >> $GITHUB_OUTPUT
+          fi
+
+          # TODO: Fail with CONFORMANCE_RC if non-zero
+          # (conformance not yet passing for this registry)
+          echo "Conformance return code: ${CONFORMANCE_RC}"
+          exit 0
+
+      - name: Upload OCI conformance results as build artifact
+        if: always() && steps.tests.outputs.has-report == 'true'
+        uses: actions/upload-artifact@v3
+        with:
+          name: oci-conformance-results-${{ matrix.go }}
+          path: |
+            ./report.html
+            ./junit.xml
